name: DocsGeneration

on: 
  release:
    types: [published]

jobs:
  deploy_docs:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Switch to Xcode 11
      run: sudo xcode-select --switch /Applications/Xcode_11.app/Contents/Developer
    - name: Generate Jazzy Docs
      uses: sdfnz/publish-jazzy-docs@master
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
        version: 0.11.0
        config: .jazzy.json

