name: DocsGeneration

on: 
  release:
    types: [published]

jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Switch to Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app/Contents/Developer
    - name: Generate Jazzy Docs
      uses: Steven0351/publish-jazzy-docs@devcontainer
      with:
        personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        version: 0.11.0
        config: .jazzy.yml

