name: DocsGeneration

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Switch to Xcode 11
      run: sudo xcode-select --switch /Applications/Xcode_11.app/Contents/Developer
    - name: Generate Jazzy Docs
      uses: steven0351/publish-jazzy-docs@initial-implementation
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
        jazzy_args: "--author Steven Sherry -o sweet/sweet/documentation --theme fullwidth"

